# Generated by Django 4.2.1 on 2023-05-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, height_field=220, upload_to='product_images', verbose_name='Фото продукта', width_field=370),
        ),
    ]
