# Generated by Django 4.2.1 on 2023-05-12 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_product_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='a7b720d6-28bc-40e7-9764-3a5f7d0ba4be',
            new_name='d7020926-f12d-48d1-92d5-8ee951d0deea',
        ),
    ]
