# Generated by Django 4.2.1 on 2023-05-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_a7b720d6_28bc_40e7_9764_3a5f7d0ba4be_product_d7020926_f12d_48d1_92d5_8ee951d0deea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='d7020926-f12d-48d1-92d5-8ee951d0deea',
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='product_images/9d6166e2-7a25-40c4-b6c0-9025b8a41028', verbose_name='Фото продукта'),
        ),
    ]
