# Generated by Django 4.2.1 on 2023-05-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_product_d7020926_f12d_48d1_92d5_8ee951d0deea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='product_images/5d33902b-ac13-444f-a519-fc189dfde026', verbose_name='Фото продукта'),
        ),
    ]
