# Generated by Django 4.2.1 on 2023-05-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_bankcard_number_user_created_at_user_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='product_images/023b21df-c628-4be1-9149-0d1546cd2a5b', verbose_name='Фото продукта'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
