# Generated by Django 4.2.1 on 2023-05-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_product_photo_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='product_images/c043822b-8345-42ce-be82-d234a4f2ae22', verbose_name='Фото продукта'),
        ),
    ]
