# Generated by Django 4.2.1 on 2023-05-21 09:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_product_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='operatingsystem',
            options={'verbose_name': 'Операционная система', 'verbose_name_plural': 'Операционные системы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-publish_date'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='product_images/776b3811-daff-48d5-83a8-c8ab5d57cb64', verbose_name='Фото продукта'),
        ),
        migrations.CreateModel(
            name='ProductKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Ключ активации продукта')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='keys', to='core.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Ключ активации продукта',
                'verbose_name_plural': 'Ключи активации продуктов',
                'ordering': ['-product'],
            },
        ),
    ]
