# Generated by Django 4.2.1 on 2023-05-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='product_images/dee09ad3-f9c5-4491-8fee-bf57610fe83c', verbose_name='Фото продукта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bankcard_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер банковской карты'),
        ),
    ]
