# Generated by Django 4.2.1 on 2023-05-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_product_photo_alter_user_bankcard_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='product_images/f1dfa268-46d4-4234-bfd9-91f3d5cf6a75', verbose_name='Фото продукта'),
        ),
    ]
