# Generated by Django 4.2.1 on 2023-05-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='product_images/5c43ae51-61dd-47c7-a6e6-d7114d4531a1', verbose_name='Фото продукта'),
        ),
    ]
