# Generated by Django 4.2.1 on 2023-05-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productkey',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Использован?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='product_images/63d4d1c8-080a-4c84-9ec1-11e1bd520439', verbose_name='Фото продукта'),
        ),
    ]
