# Generated by Django 4.2.1 on 2023-05-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_productkey_is_delete_alter_product_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productkey',
            old_name='is_delete',
            new_name='is_deleted',
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='product_images/5b01f454-ee7d-4a65-8c82-5764201b44a0', verbose_name='Фото продукта'),
        ),
    ]
